name: levio
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.4

dependencies:
  camera: ^0.12.0+1
  equatable: ^2.0.8
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  google_mlkit_pose_detection: ^0.14.1
  shake: ^3.0.0
  shared_preferences: ^2.5.5
  speech_to_text: ^7.3.0
  firebase_ai: ^3.10.0
  firebase_core: ^4.6.0
  cloud_firestore: ^6.2.0
  firebase_auth: ^6.3.0
  adaptive_platform_ui: ^0.1.104
  audioplayers: ^6.6.0
  flutter_native_splash: ^2.4.7
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"
  macos:
    generate: true
    image_path: "assets/app_icon.png"

flutter_native_splash:
  color: "#ffffff"
  image: assets/app_icon.png
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/
    - assets/icon.png
    - assets/app_icon.png
